### ISSUE TITLE
Functions to get start_of_<time unit>, end_of_<time unit>

### ISSUE THREAD

**Issue by martinsvalin** [magplus/good_times#19]
Functions for the start and end of a time_unit, accepting a datetime, or defaulting to `now` 

- `start_of_minute/1`
- `end_of_minute/1`
- `start_of_hour/1`
- `end_of_hour/1`
- `start_of_day/1`
- `end_of_day/1`
- `start_of_week/1`
- `end_of_week/1`
- `start_of_month/1`
- `end_of_month/1`
- `start_of_year/1`
- `end_of_year/1`

Example: 
```
@a_datetime {{2015, 2, 27}, {18, 30, 45}}
test "start_of_day" do
  assert start_of_day(@a_datetime) == {{2015, 2, 27}, {0, 0, 0}}
  assert start_of_day == start_of_day now
end

test "end_of_day" do
  assert end_of_day(@a_datetime) == {{2015, 2, 27}, {23, 59, 59}}
  assert end_of_day == end_of_day now
end

test "start_of_week" do
  assert start_of_week(@a_datetime) == {{2015, 2, 23}, {0, 0, 0}}
  assert start_of_week == start_of_week now
end

test "end_of_week" do
  assert end_of_week(@a_datetime) == {{2015, 3, 1}, {23, 59, 59}}
  assert end_of_week == end_of_week now
end
```

I think they would compose nicely: `start_of_month |> start_of_week` would be of interest, for example, if you're making a calendar grid. Together with `end_of_month |> end_of_week`, you'd have the date range to show for the current month.

Thoughts?

**Comment by martinsvalin** [comment]
`s/start/beginning`

**Comment by DevL** [comment]
Module name: `GoodTimes.TimeIsRelative`? :grin:

**Comment by martinsvalin** [comment]
It occurs to me that we could simply provide datetime ranges, and let people pick the start or end of the range as they like. `{start_date, _}..{end_date,_} = some_range` if they only care about the dates, for example. Only it isn't clear what the step is between them. The step for an Elixir range is defined by implementing the Range.Iterator protocol. I wonder if there's a nice way to pick between stepping seconds, minutes, hours etc.

More generally, I'd like to strike a balance of providing expressive functions (which leads us to define lots of similar functions), and providing fewer functions that compose well. I think `at` composes well. `now` is a no-brainer. But maybe `a_day_from_now` is of similar expressiveness to composing `1 |> day_after now`.

Anyway, back to ranges. The function `week_of(datetime)` could return `beginning_of_week..end_of_week`, which could easily be pattern matched.

**Comment by DevL** [comment]
I recall a goal of Elixir 1.1.0 being to restrict ranges to start and end with the same type, but since we're talking tuple to same-sized tuple that shouldn't be a concern.

Striking a balance between expressiveness and bloat is certainly one of our greatest challenges. Since we've yet to reach 1.0 and there's not that many users of the library, we could prune it if we think that's necessary. Candidates for removal would obviously be `a_<time_unit>...` and `...from_now` / `...ago` functions. We could also extract them to a separate module as they're not "core" functions.

Also, the focus of the library needs to be considered. Do we branch out into calendar-related things such as weekdays and the notion of "first Monday of the month" or do we stick to datetime arithmetic? I believe the former very well can take us down the dark path to bloathood.

But like you wrote, back to ranges.

**Comment by DevL** [comment]
A potential problem with ranges is that the basic datatype of ours isn't a struct, but rather a tuple. I'm not sure we can implement a sensible range for datetime1..datetime2 in that case.
