### ISSUE TITLE
Expand "at" to handle dates in addition to datetimes

### ISSUE THREAD

**Issue by DevL** [magplus/good_times#29]
Based on #28 and #10, we'd like to be able to write `today |> at {10, 30, 0}`, which entails that `at` should handle `date`s in addition to `datetime`s.

**Comment by DevL** [comment]
Having some trouble with this one when it comes to style.

In order to avoid having to duplicate the docstring and treat the same function as two functions _and_ in order to not mess up the output of `h GoodTimes.at` in iex, one the following three versions can be used.

Common for all (yes typespecs can be overloaded and both will show up using `s GoodTimes.at` in iex):
```elixir
@doc """
  Merges the date from the given date or datetime with the given time.

  ## Examples

      iex> now |> at {10, 30, 15}
      {{2015, 2, 27}, {10, 30, 15}}
      iex> {2015, 2, 27} |> at {10, 30, 15}
      {{2015, 2, 27}, {10, 30, 15}}
  """
  @spec at(date, time) :: datetime
  @spec at(datetime, time) :: datetime
```

### Version 1
```elixir
  def at(date_or_datetime, time), do: _at(date_or_datetime, time)
  defp _at({date, _}, time), do: {date, time}
  defp _at(date, time), do: {date, time}
```
Not completely sold on having to dispatch to `_at` functions, but at least the documented interface is clear and the individual functions aren't confusing regarding what argument they take.


### Version 2
```elixir
  def at({date, _}, time), do: {date, time}
  def at(date_or_datetime, time), do: {date_or_datetime, time}
```
Smallest version, but an argument that's _clearly_ a `date` is named `date_or_datetime` to have `h` and generated docs to show up properly. There's no secondary dispatching going on though, so it's also the most efficient version.


### Version 3
```elixir
  def at(date_or_datetime, time) do
    case date_or_datetime do
      {date, _} -> {date, time}
      date -> {date, time}
    end
  end
```
Uhm...just no. There's an initial level of dispatching here, just like version 1, but less clear.


Thoughts?

**Comment by martinsvalin** [comment]
So the problem, as I understand it, is that `h at` will show `at(arg1, time)` if we do the simplest thing possible (i.e `def at({date,_}, time), do: {date, time}` and `def at(date, time), do: {date, time}`?

In that case, I prefer version 1. It's not misleading about incoming arguments, and it is, I think, the most idiomatic version of the three. But to be honest, we're showing `arg1` style output in the documentation for several other functions. Should we change them as well? I think it would be more reasonable to see if we can improve the help documentation so that it pulls the argument type from the `@spec`.

Another question: should we do `defp _at({date, _}, time), do: _at(date, time)`? I'm on the fence, since the implementation is just sooo simple.

**Comment by DevL** [comment]
Version 1 it is then. Regarding adding another level of indirection, nah. That's just waste in this case given the triviality of the do block.
